<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UpazilaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $upazila = [
            ['district_id'=>'1',  'bn_name'=>'দেবিদ্বার','name'=>'Debidwar'],
            ['district_id'=>'1',  'bn_name'=>'বরুড়া','name'=>'Barura'],
            ['district_id'=>'1',  'bn_name'=>'ব্রাহ্মণপাড়া','name'=>'Brahmanpara'],
            ['district_id'=>'1',  'bn_name'=>'চান্দিনা','name'=>'Chandina'],
            ['district_id'=>'1',  'bn_name'=>'চৌদ্দগ্রাম','name'=>'Chauddagram'],
            ['district_id'=>'1',  'bn_name'=>'দাউদকান্দি','name'=>'Daudkandi'],
            ['district_id'=>'1',  'bn_name'=>'হোমনা','name'=>'Homna'],
            ['district_id'=>'1',  'bn_name'=>'লাকসাম','name'=>'Laksam'],
            ['district_id'=>'1',  'bn_name'=>'মুরাদনগর','name'=>'Muradnagar'],
            ['district_id'=>'1',  'bn_name'=>'নাঙ্গলকোট','name'=>'Nangalkot'],
            ['district_id'=>'1',  'bn_name'=>'কুমিল্লা সদর','name'=>'Comilla Sadar'],
            ['district_id'=>'1',  'bn_name'=>'মেঘনা','name'=>'Meghna'],
            ['district_id'=>'1',  'bn_name'=>'মনোহরগঞ্জ','name'=>'Monohargonj'],
            ['district_id'=>'1',  'bn_name'=>'সদর দক্ষিণ','name'=>'Sadarsouth'],
            ['district_id'=>'1',  'bn_name'=>'তিতাস','name'=>'Titas'],
            ['district_id'=>'1',  'bn_name'=>'বুড়িচং','name'=>'Burichang'],
            ['district_id'=>'1',  'bn_name'=>'লালমাই','name'=>'Lalmai'],
            ['district_id'=>'2',  'bn_name'=>'ছাগলনাইয়া','name'=>'Chhagalnaiya'],
            ['district_id'=>'2',  'bn_name'=>'ফেনী সদর','name'=>'Feni Sadar'],
            ['district_id'=>'2',  'bn_name'=>'সোনাগাজী','name'=>'Sonagazi'],
            ['district_id'=>'2',  'bn_name'=>'ফুলগাজী','name'=>'Fulgazi'],
            ['district_id'=>'2',  'bn_name'=>'পরশুরাম','name'=>'Parshuram'],
            ['district_id'=>'2',  'bn_name'=>'দাগনভূঞা','name'=>'Daganbhuiyan'],
            ['district_id'=>'3',  'bn_name'=>'ব্রাহ্মণবাড়িয়া সদর','name'=>'Brahmanbaria Sadar' ],
            ['district_id'=>'3',  'bn_name'=>'কসবা','name'=>'Kasba'],
            ['district_id'=>'3',  'bn_name'=>'নাসিরনগর','name'=>'Nasirnagar'],
            ['district_id'=>'3',  'bn_name'=>'সরাইল','name'=>'Sarail'],
            ['district_id'=>'3',  'bn_name'=>'আশুগঞ্জ','name'=>'Ashuganj'],
            ['district_id'=>'3',  'bn_name'=>'আখাউড়া','name'=>'Akhaura'],
            ['district_id'=>'3',  'bn_name'=>'নবীনগর','name'=>'Nabinagar'],
            ['district_id'=>'3',  'bn_name'=>'বাঞ্ছারামপুর','name'=>'Bancharampur'],
            ['district_id'=>'3',  'bn_name'=>'বিজয়নগর','name'=>'Bijoynagar'],
            ['district_id'=>'4',  'bn_name'=>'রাঙ্গামাটি সদর','name'=>'Rangamati Sadar'],
            ['district_id'=>'4',  'bn_name'=>'কাপ্তাই','name'=>'Kaptai'],
            ['district_id'=>'4',  'bn_name'=>'কাউখালী','name'=>'Kawkhali'],
            ['district_id'=>'4',  'bn_name'=>'বাঘাইছড়ি','name'=>'Baghaichari'],
            ['district_id'=>'4',  'bn_name'=>'বরকল','name'=>'Barkal'],
            ['district_id'=>'4',  'bn_name'=>'লংগদু','name'=>'Langadu'],
            ['district_id'=>'4',  'bn_name'=>'রাজস্থলী','name'=>'Rajasthali'],
            ['district_id'=>'4',  'bn_name'=>'বিলাইছড়ি','name'=>'Belaichari'],
            ['district_id'=>'4',  'bn_name'=>'জুরাছড়ি','name'=>'Juraichari'],
            ['district_id'=>'4',  'bn_name'=>'নানিয়ারচর','name'=>'Naniarchar'],
            ['district_id'=>'5',  'bn_name'=>'নোয়াখালী সদর','name'=>'Noakhali Sadar'],
            ['district_id'=>'5',  'bn_name'=>'কোম্পানীগঞ্জ','name'=>'Companiganj'],
            ['district_id'=>'5',  'bn_name'=>'বেগমগঞ্জ','name'=>'Begumganj'],
            ['district_id'=>'5',  'bn_name'=>'হাতিয়া','name'=>'Hatia'],
            ['district_id'=>'5',  'bn_name'=>'সুবর্ণচর','name'=>'Subarnachar'],
            ['district_id'=>'5',  'bn_name'=>'কবিরহাট','name'=>'Kabirhat'],
            ['district_id'=>'5',  'bn_name'=>'সেনবাগ','name'=>'Senbug'],
            ['district_id'=>'5',  'bn_name'=>'চাটখিল','name'=>'Chatkhil'],
            ['district_id'=>'5',  'bn_name'=>'সোনাইমুড়ী','name'=>'Sonaimori'],
            ['district_id'=>'6',  'bn_name'=>'হাইমচর','name'=>'Haimchar'],
            ['district_id'=>'6',  'bn_name'=>'কচুয়া','name'=>'Kachua'],
            ['district_id'=>'6',  'bn_name'=>'শাহরাস্তি','name'=>'Shahrasti'],
            ['district_id'=>'6',  'bn_name'=>'চাঁদপুর সদর','name'=>'Chandpur Sadar'],
            ['district_id'=>'6',  'bn_name'=>'মতলব দক্ষিণ','name'=>'Matlab South'],
            ['district_id'=>'6',  'bn_name'=>'হাজীগঞ্জ','name'=>'Hajiganj'],
            ['district_id'=>'6',  'bn_name'=>'মতলব উত্তর','name'=>'Matlab North'],
            ['district_id'=>'6',  'bn_name'=>'ফরিদগঞ্জ','name'=>'Faridgonj'],
            ['district_id'=>'7',  'bn_name'=>'লক্ষ্মীপুর সদর','name'=>'Lakshmipur Sadar'],
            ['district_id'=>'7',  'bn_name'=>'কমলনগর','name'=>'Kamalnagar'],
            ['district_id'=>'7',  'bn_name'=>'রায়পুর','name'=>'Raipur'],
            ['district_id'=>'7',  'bn_name'=>'রামগতি','name'=>'Ramgati'],
            ['district_id'=>'7',  'bn_name'=>'রামগঞ্জ','name'=>'Ramganj'],
            ['district_id'=>'8',  'bn_name'=>'রাঙ্গুনিয়া','name'=>'Rangunia'],
            ['district_id'=>'8',  'bn_name'=>'সীতাকুন্ড','name'=>'Sitakunda'],
            ['district_id'=>'8',  'bn_name'=>'মীরসরাই','name'=>'Mirsharai'],
            ['district_id'=>'8',  'bn_name'=>'পটিয়া','name'=>'Patiya'],
            ['district_id'=>'8',  'bn_name'=>'সন্দ্বীপ','name'=>'Sandwip'],
            ['district_id'=>'8',  'bn_name'=>'বাঁশখালী','name'=>'Banshkhali'],
            ['district_id'=>'8',  'bn_name'=>'বোয়ালখালী','name'=>'Boalkhali'],
            ['district_id'=>'8',  'bn_name'=>'আনোয়ারা','name'=>'Anwara'],
            ['district_id'=>'8',  'bn_name'=>'চন্দনাইশ','name'=>'Chandanaish'],
            ['district_id'=>'8',  'bn_name'=>'সাতকানিয়া','name'=>'Satkania'],
            ['district_id'=>'8',  'bn_name'=>'লোহাগাড়া','name'=>'Lohagara'],
            ['district_id'=>'8',  'bn_name'=>'হাটহাজারী','name'=>'Hathazari'],
            ['district_id'=>'8',  'bn_name'=>'ফটিকছড়ি','name'=>'Fatikchhari'],
            ['district_id'=>'8',  'bn_name'=>'রাউজান','name'=>'Raozan'],
            ['district_id'=>'8',  'bn_name'=>'কর্ণফুলী','name'=>'Karnafuli'],
            ['district_id'=>'9',  'bn_name'=>'কক্সবাজার সদর','name'=>'Coxsbazar Sadar'],
            ['district_id'=>'9',  'bn_name'=>'চকরিয়া','name'=>'Chakaria'],
            ['district_id'=>'9',  'bn_name'=>'কুতুবদিয়া','name'=>'Kutubdia'],
            ['district_id'=>'9',  'bn_name'=>'উখিয়া','name'=>'Ukhiya'],
            ['district_id'=>'9',  'bn_name'=>'মহেশখালী','name'=>'Moheshkhali'],
            ['district_id'=>'9',  'bn_name'=>'পেকুয়া','name'=>'Pekua'],
            ['district_id'=>'9',  'bn_name'=>'রামু','name'=>'Ramu'],
            ['district_id'=>'9',  'bn_name'=>'টেকনাফ','name'=>'Teknaf'],
            ['district_id'=>'10', 'bn_name'=>'খাগড়াছড়ি সদর', 'name'=>'Khagrachhari Sadar'],
            ['district_id'=>'10', 'bn_name'=>'দিঘীনালা', 'name'=>'Dighinala'],
            ['district_id'=>'10', 'bn_name'=>'পানছড়ি', 'name'=>'Panchari'],
            ['district_id'=>'10', 'bn_name'=>'লক্ষীছড়ি', 'name'=>'Laxmichhari'],
            ['district_id'=>'10', 'bn_name'=>'মহালছড়ি', 'name'=>'Mohalchari'],
            ['district_id'=>'10', 'bn_name'=>'মানিকছড়ি', 'name'=>'Manikchari'],
            ['district_id'=>'10', 'bn_name'=>'রামগড়', 'name'=>'Ramgarh'],
            ['district_id'=>'10', 'bn_name'=>'মাটিরাঙ্গা', 'name'=>'Matiranga'],
            ['district_id'=>'10', 'bn_name'=>'গুইমারা', 'name'=>'Guimara'],
            ['district_id'=>'11', 'bn_name'=>'বান্দরবান সদর', 'name'=>'Bandarban Sadar'],
            ['district_id'=>'11', 'bn_name'=>'আলীকদম', 'name'=>'Alikadam'],
            ['district_id'=>'11', 'bn_name'=>'নাইক্ষ্যংছড়ি', 'name'=>'Naikhongchhari'],
            ['district_id'=>'11', 'bn_name'=>'রোয়াংছড়ি', 'name'=>'Rowangchhari'],
            ['district_id'=>'11', 'bn_name'=>'লামা', 'name'=>'Lama'],
            ['district_id'=>'11', 'bn_name'=>'রুমা', 'name'=>'Ruma'],
            ['district_id'=>'11', 'bn_name'=>'থানচি', 'name'=>'Thanchi'],
            ['district_id'=>'12', 'bn_name'=>'বেলকুচি', 'name'=>'Belkuchi'],
            ['district_id'=>'12', 'bn_name'=>'চৌহালি', 'name'=>'Chauhali'],
            ['district_id'=>'12', 'bn_name'=>'কামারখন্দ', 'name'=>'Kamarkhand'],
            ['district_id'=>'12', 'bn_name'=>'কাজীপুর', 'name'=>'Kazipur'],
            ['district_id'=>'12', 'bn_name'=>'রায়গঞ্জ', 'name'=>'Raigonj'],
            ['district_id'=>'12', 'bn_name'=>'শাহজাদপুর', 'name'=>'Shahjadpur'],
            ['district_id'=>'12', 'bn_name'=>'সিরাজগঞ্জ সদর', 'name'=>'Sirajganj Sadar'],
            ['district_id'=>'12', 'bn_name'=>'তাড়াশ', 'name'=>'Tarash'],
            ['district_id'=>'12', 'bn_name'=>'উল্লাপাড়া', 'name'=>'Ullapara'],
            ['district_id'=>'13', 'bn_name'=>'সুজানগর', 'name'=>'Sujanagar'],
            ['district_id'=>'13', 'bn_name'=>'ঈশ্বরদী', 'name'=>'Ishurdi'],
            ['district_id'=>'13', 'bn_name'=>'ভাঙ্গুড়া', 'name'=>'Bhangura'],
            ['district_id'=>'13', 'bn_name'=>'পাবনা সদর', 'name'=>'Pabna Sadar'],
            ['district_id'=>'13', 'bn_name'=>'বেড়া', 'name'=>'Bera'],
            ['district_id'=>'13', 'bn_name'=>'আটঘরিয়া', 'name'=>'Atghoria'],
            ['district_id'=>'13', 'bn_name'=>'চাটমোহর', 'name'=>'Chatmohar'],
            ['district_id'=>'13', 'bn_name'=>'সাঁথিয়া', 'name'=>'Santhia'],
            ['district_id'=>'13', 'bn_name'=>'ফরিদপুর', 'name'=>'Faridpur'],
            ['district_id'=>'14', 'bn_name'=>'কাহালু', 'name'=>'Kahaloo'],
            ['district_id'=>'14', 'bn_name'=>'বগুড়া সদর', 'name'=>'Bogura Sadar'],
            ['district_id'=>'14', 'bn_name'=>'সারিয়াকান্দি', 'name'=>'Shariakandi'],
            ['district_id'=>'14', 'bn_name'=>'শাজাহানপুর', 'name'=>'Shajahanpur'],
            ['district_id'=>'14', 'bn_name'=>'দুপচাচিঁয়া', 'name'=>'Dupchanchia'],
            ['district_id'=>'14', 'bn_name'=>'আদমদিঘি', 'name'=>'Adamdighi'],
            ['district_id'=>'14', 'bn_name'=>'নন্দিগ্রাম', 'name'=>'Nondigram'],
            ['district_id'=>'14', 'bn_name'=>'সোনাতলা', 'name'=>'Sonatala'],
            ['district_id'=>'14', 'bn_name'=>'ধুনট', 'name'=>'Dhunot'],
            ['district_id'=>'14', 'bn_name'=>'গাবতলী', 'name'=>'Gabtali'],
            ['district_id'=>'14', 'bn_name'=>'শেরপুর', 'name'=>'Sherpur'],
            ['district_id'=>'14', 'bn_name'=>'শিবগঞ্জ', 'name'=>'Shibganj'],
            ['district_id'=>'15', 'bn_name'=>'পবা', 'name'=>'Paba'],
            ['district_id'=>'15', 'bn_name'=>'দুর্গাপুর', 'name'=>'Durgapur'],
            ['district_id'=>'15', 'bn_name'=>'মোহনপুর', 'name'=>'Mohonpur'],
            ['district_id'=>'15', 'bn_name'=>'চারঘাট', 'name'=>'Charghat'],
            ['district_id'=>'15', 'bn_name'=>'পুঠিয়া', 'name'=>'Puthia'],
            ['district_id'=>'15', 'bn_name'=>'বাঘা', 'name'=>'Bagha'],
            ['district_id'=>'15', 'bn_name'=>'গোদাগাড়ী', 'name'=>'Godagari'],
            ['district_id'=>'15', 'bn_name'=>'তানোর', 'name'=>'Tanore'],
            ['district_id'=>'15', 'bn_name'=>'বাগমারা', 'name'=>'Bagmara'],
            ['district_id'=>'16', 'bn_name'=>'নাটোর সদর', 'name'=>'Natore Sadar'],
            ['district_id'=>'16', 'bn_name'=>'সিংড়া', 'name'=>'Singra'],
            ['district_id'=>'16', 'bn_name'=>'বড়াইগ্রাম', 'name'=>'Baraigram'],
            ['district_id'=>'16', 'bn_name'=>'বাগাতিপাড়া', 'name'=>'Bagatipara'],
            ['district_id'=>'16', 'bn_name'=>'লালপুর', 'name'=>'Lalpur'],
            ['district_id'=>'16', 'bn_name'=>'গুরুদাসপুর', 'name'=>'Gurudaspur'],
            ['district_id'=>'16', 'bn_name'=>'নলডাঙ্গা', 'name'=>'Naldanga'],
            ['district_id'=>'17', 'bn_name'=>'আক্কেলপুর', 'name'=>'Akkelpur'],
            ['district_id'=>'17', 'bn_name'=>'কালাই', 'name'=>'Kalai'],
            ['district_id'=>'17', 'bn_name'=>'ক্ষেতলাল', 'name'=>'Khetlal'],
            ['district_id'=>'17', 'bn_name'=>'পাঁচবিবি', 'name'=>'Panchbibi'],
            ['district_id'=>'17', 'bn_name'=>'জয়পুরহাট সদর', 'name'=>'Joypurhat Sadar'],
            ['district_id'=>'18', 'bn_name'=>'চাঁপাইনবাবগঞ্জ সদর', 'name'=>'Chapainawabganj Sadar'],
            ['district_id'=>'18', 'bn_name'=>'গোমস্তাপুর', 'name'=>'Gomostapur'],
            ['district_id'=>'18', 'bn_name'=>'নাচোল', 'name'=>'Nachol'],
            ['district_id'=>'18', 'bn_name'=>'ভোলাহাট', 'name'=>'Bholahat'],
            ['district_id'=>'18', 'bn_name'=>'শিবগঞ্জ', 'name'=>'Shibganj'],
            ['district_id'=>'19', 'bn_name'=>'মহাদেবপুর', 'name'=> 'Mohadevpur'],
            ['district_id'=>'19', 'bn_name'=>'বদলগাছী', 'name'=> 'Badalgachi'],
            ['district_id'=>'19', 'bn_name'=>'পত্নিতলা', 'name'=> 'Patnitala'],
            ['district_id'=>'19', 'bn_name'=>'ধামইরহাট', 'name'=> 'Dhamoirhat'],
            ['district_id'=>'19', 'bn_name'=>'নিয়ামতপুর', 'name'=> 'Niamatpur'],
            ['district_id'=>'19', 'bn_name'=>'মান্দা', 'name'=> 'Manda'],
            ['district_id'=>'19', 'bn_name'=>'আত্রাই', 'name'=> 'Atrai'],
            ['district_id'=>'19', 'bn_name'=>'রাণীনগর', 'name'=> 'Raninagar'],
            ['district_id'=>'19', 'bn_name'=>'নওগাঁ সদর', 'name'=> 'Naogaon Sadar'],
            ['district_id'=>'19', 'bn_name'=>'পোরশা', 'name'=> 'Porsha'],
            ['district_id'=>'19', 'bn_name'=>'সাপাহার', 'name'=> 'Sapahar'],
            ['district_id'=>'20', 'bn_name'=>'মণিরামপুর', 'name'=>'Manirampur'],
            ['district_id'=>'20', 'bn_name'=>'অভয়নগর', 'name'=>'Abhaynagar'],
            ['district_id'=>'20', 'bn_name'=>'বাঘারপাড়া', 'name'=>'Bagherpara'],
            ['district_id'=>'20', 'bn_name'=>'চৌগাছা', 'name'=>'Chougachha'],
            ['district_id'=>'20', 'bn_name'=>'ঝিকরগাছা', 'name'=>'Jhikargacha'],
            ['district_id'=>'20', 'bn_name'=>'কেশবপুর', 'name'=>'Keshabpur'],
            ['district_id'=>'20', 'bn_name'=>'যশোর সদর', 'name'=>'Jessore Sadar'],
            ['district_id'=>'20', 'bn_name'=>'শার্শা', 'name'=>'Sharsha'],
            ['district_id'=>'21', 'bn_name'=>'আশাশুনি', 'name'=>'Assasuni'],
            ['district_id'=>'21', 'bn_name'=>'দেবহাটা', 'name'=>'Debhata'],
            ['district_id'=>'21', 'bn_name'=>'কলারোয়া', 'name'=>'Kalaroa'],
            ['district_id'=>'21', 'bn_name'=>'সাতক্ষীরা সদর', 'name'=>'Satkhira Sadar'],
            ['district_id'=>'21', 'bn_name'=>'শ্যামনগর', 'name'=>'Shyamnagar'],
            ['district_id'=>'21', 'bn_name'=>'তালা', 'name'=>'Tala'],
            ['district_id'=>'21', 'bn_name'=>'কালিগঞ্জ', 'name'=>'Kaliganj'],
            ['district_id'=>'22', 'bn_name'=>'মুজিবনগর', 'name'=>'Mujibnagar'],
            ['district_id'=>'22', 'bn_name'=>'মেহেরপুর সদর', 'name'=>'Meherpur Sadar'],
            ['district_id'=>'22', 'bn_name'=>'গাংনী', 'name'=>'Gangni'],
            ['district_id'=>'23', 'bn_name'=>'নড়াইল সদর', 'name'=>'Narail Sadar'],
            ['district_id'=>'23', 'bn_name'=>'লোহাগড়া', 'name'=>'Lohagara'],
            ['district_id'=>'23', 'bn_name'=>'কালিয়া', 'name'=>'Kalia'],
            ['district_id'=>'24', 'bn_name'=>'চুয়াডাঙ্গা সদর', 'name'=>'Chuadanga Sadar'],
            ['district_id'=>'24', 'bn_name'=>'আলমডাঙ্গা', 'name'=>'Alamdanga'],
            ['district_id'=>'24', 'bn_name'=>'দামুড়হুদা', 'name'=>'Damurhuda'],
            ['district_id'=>'24', 'bn_name'=>'জীবননগর', 'name'=>'Jibannagar'],
            ['district_id'=>'25', 'bn_name'=>'কুষ্টিয়া সদর', 'name'=>'Kushtia Sadar'],
            ['district_id'=>'25', 'bn_name'=>'কুমারখালী', 'name'=>'Kumarkhali'],
            ['district_id'=>'25', 'bn_name'=>'খোকসা', 'name'=>'Khoksa'],
            ['district_id'=>'25', 'bn_name'=>'মিরপুর', 'name'=>'Mirpur'],
            ['district_id'=>'25', 'bn_name'=>'দৌলতপুর', 'name'=>'Daulatpur'],
            ['district_id'=>'25', 'bn_name'=>'ভেড়ামারা', 'name'=>'Bheramara'],
            ['district_id'=>'26', 'bn_name'=>'শালিখা', 'name'=>'Shalikha'],
            ['district_id'=>'26', 'bn_name'=>'শ্রীপুর', 'name'=>'Sreepur'],
            ['district_id'=>'26', 'bn_name'=>'মাগুরা সদর', 'name'=>'Magura Sadar'],
            ['district_id'=>'26', 'bn_name'=>'মোহাম্মদপুর', 'name'=>'Mohammadpur'],
            ['district_id'=>'27', 'bn_name'=>'পাইকগাছা', 'name'=>'Paikgasa'],
            ['district_id'=>'27', 'bn_name'=>'ফুলতলা', 'name'=>'Fultola'],
            ['district_id'=>'27', 'bn_name'=>'দিঘলিয়া', 'name'=>'Digholia'],
            ['district_id'=>'27', 'bn_name'=>'রূপসা', 'name'=>'Rupsha'],
            ['district_id'=>'27', 'bn_name'=>'তেরখাদা', 'name'=>'Terokhada'],
            ['district_id'=>'27', 'bn_name'=>'ডুমুরিয়া', 'name'=>'Dumuria'],
            ['district_id'=>'27', 'bn_name'=>'বটিয়াঘাটা', 'name'=>'Botiaghata'],
            ['district_id'=>'27', 'bn_name'=>'দাকোপ', 'name'=>'Dakop'],
            ['district_id'=>'27', 'bn_name'=>'কয়রা', 'name'=>'Koyra'],
            ['district_id'=>'28', 'bn_name'=>'ফকিরহাট', 'name'=>'Fakirhat'],
            ['district_id'=>'28', 'bn_name'=>'বাগেরহাট সদর', 'name'=>'Bagerhat Sadar'],
            ['district_id'=>'28', 'bn_name'=>'মোল্লাহাট', 'name'=>'Mollahat'],
            ['district_id'=>'28', 'bn_name'=>'শরণখোলা', 'name'=>'Sarankhola'],
            ['district_id'=>'28', 'bn_name'=>'রামপাল', 'name'=>'Rampal'],
            ['district_id'=>'28', 'bn_name'=>'মোড়েলগঞ্জ', 'name'=>'Morrelganj'],
            ['district_id'=>'28', 'bn_name'=>'কচুয়া', 'name'=>'Kachua'],
            ['district_id'=>'28', 'bn_name'=>'মোংলা', 'name'=>'Mongla'],
            ['district_id'=>'28', 'bn_name'=>'চিতলমারী', 'name'=>'Chitalmari'],
            ['district_id'=>'29', 'bn_name'=>'ঝিনাইদহ সদর', 'name'=>'Jhenaidah Sadar'],
            ['district_id'=>'29', 'bn_name'=>'শৈলকুপা', 'name'=>'Shailkupa'],
            ['district_id'=>'29', 'bn_name'=>'হরিণাকুন্ডু', 'name'=>'Harinakundu'],
            ['district_id'=>'29', 'bn_name'=>'কালীগঞ্জ', 'name'=>'Kaliganj'],
            ['district_id'=>'29', 'bn_name'=>'কোটচাঁদপুর', 'name'=>'Kotchandpur'],
            ['district_id'=>'29', 'bn_name'=>'মহেশপুর', 'name'=>'Moheshpur'],
            ['district_id'=>'30', 'bn_name'=>'ঝালকাঠি সদর', 'name'=>'Jhalakathi Sadar'],
            ['district_id'=>'30', 'bn_name'=>'কাঠালিয়া', 'name'=>'Kathalia'],
            ['district_id'=>'30', 'bn_name'=>'নলছিটি', 'name'=>'Nalchity'],
            ['district_id'=>'30', 'bn_name'=>'রাজাপুর', 'name'=>'Rajapur'],
            ['district_id'=>'31', 'bn_name'=>'বাউফল', 'name'=>'Bauphal'],
            ['district_id'=>'31', 'bn_name'=>'পটুয়াখালী সদর', 'name'=>'Patuakhali Sadar'],
            ['district_id'=>'31', 'bn_name'=>'দুমকি', 'name'=>'Dumki'],
            ['district_id'=>'31', 'bn_name'=>'দশমিনা', 'name'=>'Dashmina'],
            ['district_id'=>'31', 'bn_name'=>'কলাপাড়া', 'name'=>'Kalapara'],
            ['district_id'=>'31', 'bn_name'=>'মির্জাগঞ্জ', 'name'=>'Mirzaganj'],
            ['district_id'=>'31', 'bn_name'=>'গলাচিপা', 'name'=>'Galachipa'],
            ['district_id'=>'31', 'bn_name'=>'রাঙ্গাবালী', 'name'=>'Rangabali'],
            ['district_id'=>'32', 'bn_name'=>'পিরোজপুর সদর', 'name'=>'Pirojpur Sadar'],
            ['district_id'=>'32', 'bn_name'=>'নাজিরপুর', 'name'=>'Nazirpur'],
            ['district_id'=>'32', 'bn_name'=>'কাউখালী', 'name'=>'Kawkhali'],
            ['district_id'=>'32', 'bn_name'=>'জিয়ানগর', 'name'=>'Zianagar'],
            ['district_id'=>'32', 'bn_name'=>'ভান্ডারিয়া', 'name'=>'Bhandaria'],
            ['district_id'=>'32', 'bn_name'=>'মঠবাড়ীয়া', 'name'=>'Mathbaria'],
            ['district_id'=>'32', 'bn_name'=>'নেছারাবাদ', 'name'=>'Nesarabad'],
            ['district_id'=>'33', 'bn_name'=>'বরিশাল সদর', 'name'=>'Barisal Sadar'],
            ['district_id'=>'33', 'bn_name'=>'বাকেরগঞ্জ', 'name'=>'Bakerganj'],
            ['district_id'=>'33', 'bn_name'=>'বাবুগঞ্জ', 'name'=>'Babuganj'],
            ['district_id'=>'33', 'bn_name'=>'উজিরপুর', 'name'=>'Wazirpur'],
            ['district_id'=>'33', 'bn_name'=>'বানারীপাড়া', 'name'=>'Banaripara'],
            ['district_id'=>'33', 'bn_name'=>'গৌরনদী', 'name'=>'Gournadi'],
            ['district_id'=>'33', 'bn_name'=>'আগৈলঝাড়া', 'name'=>'Agailjhara'],
            ['district_id'=>'33', 'bn_name'=>'মেহেন্দিগঞ্জ', 'name'=>'Mehendiganj'],
            ['district_id'=>'33', 'bn_name'=>'মুলাদী', 'name'=>'Muladi'],
            ['district_id'=>'33', 'bn_name'=>'হিজলা', 'name'=>'Hizla'],
            ['district_id'=>'34', 'bn_name'=>'ভোলা সদর', 'name'=>'Bhola Sadar'],
            ['district_id'=>'34', 'bn_name'=>'বোরহান উদ্দিন', 'name'=>'Borhan Uddin'],
            ['district_id'=>'34', 'bn_name'=>'চরফ্যাশন', 'name'=>'Charfesson'],
            ['district_id'=>'34', 'bn_name'=>'দৌলতখান', 'name'=>'Doulatkhan'],
            ['district_id'=>'34', 'bn_name'=>'মনপুরা', 'name'=>'Monpura'],
            ['district_id'=>'34', 'bn_name'=>'তজুমদ্দিন', 'name'=>'Tazumuddin'],
            ['district_id'=>'34', 'bn_name'=>'লালমোহন', 'name'=>'Lalmohan'],
            ['district_id'=>'35', 'bn_name'=>'আমতলী', 'name'=>'Amtali'],
            ['district_id'=>'35', 'bn_name'=>'বরগুনা সদর', 'name'=>'Barguna Sadar'],
            ['district_id'=>'35', 'bn_name'=>'বেতাগী', 'name'=>'Betagi'],
            ['district_id'=>'35', 'bn_name'=>'বামনা', 'name'=>'Bamna'],
            ['district_id'=>'35', 'bn_name'=>'পাথরঘাটা', 'name'=>'Pathorghata'],
            ['district_id'=>'35', 'bn_name'=>'তালতলি', 'name'=>'Taltali'],
            ['district_id'=>'36', 'bn_name'=>'বালাগঞ্জ', 'name'=>'Balaganj'],
            ['district_id'=>'36', 'bn_name'=>'বিয়ানীবাজার', 'name'=>'Beanibazar'],
            ['district_id'=>'36', 'bn_name'=>'বিশ্বনাথ', 'name'=>'Bishwanath'],
            ['district_id'=>'36', 'bn_name'=>'কোম্পানীগঞ্জ', 'name'=>'Companiganj'],
            ['district_id'=>'36', 'bn_name'=>'ফেঞ্চুগঞ্জ', 'name'=>'Fenchuganj'],
            ['district_id'=>'36', 'bn_name'=>'গোলাপগঞ্জ', 'name'=>'Golapganj'],
            ['district_id'=>'36', 'bn_name'=>'গোয়াইনঘাট', 'name'=>'Gowainghat'],
            ['district_id'=>'36', 'bn_name'=>'জৈন্তাপুর', 'name'=>'Jaintiapur'],
            ['district_id'=>'36', 'bn_name'=>'কানাইঘাট', 'name'=>'Kanaighat'],
            ['district_id'=>'36', 'bn_name'=>'সিলেট সদর', 'name'=>'Sylhet Sadar'],
            ['district_id'=>'36', 'bn_name'=>'জকিগঞ্জ', 'name'=>'Zakiganj'],
            ['district_id'=>'36', 'bn_name'=>'দক্ষিণ সুরমা', 'name'=>'Dakshinsurma'],
            ['district_id'=>'36', 'bn_name'=>'ওসমানী নগর', 'name'=>'Osmaninagar'],
            ['district_id'=>'37', 'bn_name'=>'বড়লেখা', 'name'=>'Barlekha'],
            ['district_id'=>'37', 'bn_name'=>'কমলগঞ্জ', 'name'=>'Kamolganj'],
            ['district_id'=>'37', 'bn_name'=>'কুলাউড়া', 'name'=>'Kulaura'],
            ['district_id'=>'37', 'bn_name'=>'মৌলভীবাজার সদর', 'name'=>'Moulvibazar Sadar'],
            ['district_id'=>'37', 'bn_name'=>'রাজনগর', 'name'=>'Rajnagar'],
            ['district_id'=>'37', 'bn_name'=>'শ্রীমঙ্গল', 'name'=>'Sreemangal'],
            ['district_id'=>'37', 'bn_name'=>'জুড়ী', 'name'=>'Juri'],
            ['district_id'=>'38', 'bn_name'=>'নবীগঞ্জ', 'name'=>'Nabiganj'],
            ['district_id'=>'38', 'bn_name'=>'বাহুবল', 'name'=>'Bahubal'],
            ['district_id'=>'38', 'bn_name'=>'আজমিরীগঞ্জ', 'name'=>'Ajmiriganj'],
            ['district_id'=>'38', 'bn_name'=>'বানিয়াচং', 'name'=>'Baniachong'],
            ['district_id'=>'38', 'bn_name'=>'লাখাই', 'name'=>'Lakhai'],
            ['district_id'=>'38', 'bn_name'=>'চুনারুঘাট', 'name'=>'Chunarughat'],
            ['district_id'=>'38', 'bn_name'=>'হবিগঞ্জ সদর', 'name'=>'Habiganj Sadar'],
            ['district_id'=>'38', 'bn_name'=>'মাধবপুর', 'name'=>'Madhabpur'],
            ['district_id'=>'39', 'bn_name'=>'সুনামগঞ্জ সদর', 'name'=>'Sunamganj Sadar'],
            ['district_id'=>'39', 'bn_name'=>'দক্ষিণ সুনামগঞ্জ', 'name'=>'South Sunamganj'],
            ['district_id'=>'39', 'bn_name'=>'বিশ্বম্ভরপুর', 'name'=>'Bishwambarpur'],
            ['district_id'=>'39', 'bn_name'=>'ছাতক', 'name'=>'Chhatak'],
            ['district_id'=>'39', 'bn_name'=>'জগন্নাথপুর', 'name'=>'Jagannathpur'],
            ['district_id'=>'39', 'bn_name'=>'দোয়ারাবাজার', 'name'=>'Dowarabazar'],
            ['district_id'=>'39', 'bn_name'=>'তাহিরপুর', 'name'=>'Tahirpur'],
            ['district_id'=>'39', 'bn_name'=>'ধর্মপাশা', 'name'=>'Dharmapasha'],
            ['district_id'=>'39', 'bn_name'=>'জামালগঞ্জ', 'name'=>'Jamalganj'],
            ['district_id'=>'39', 'bn_name'=>'শাল্লা', 'name'=>'Shalla'],
            ['district_id'=>'39', 'bn_name'=>'দিরাই', 'name'=>'Derai'],
            ['district_id'=>'40', 'bn_name'=>'বেলাবো', 'name'=>'Belabo'],
            ['district_id'=>'40', 'bn_name'=>'মনোহরদী', 'name'=>'Monohardi'],
            ['district_id'=>'40', 'bn_name'=>'নরসিংদী সদর', 'name'=>'Narsingdi Sadar'],
            ['district_id'=>'40', 'bn_name'=>'পলাশ', 'name'=>'Palash'],
            ['district_id'=>'40', 'bn_name'=>'রায়পুরা', 'name'=>'Raipura'],
            ['district_id'=>'40', 'bn_name'=>'শিবপুর', 'name'=>'Shibpur'],
            ['district_id'=>'41', 'bn_name'=>'কালীগঞ্জ', 'name'=>'Kaliganj'],
            ['district_id'=>'41', 'bn_name'=>'কালিয়াকৈর', 'name'=>'Kaliakair'],
            ['district_id'=>'41', 'bn_name'=>'কাপাসিয়া', 'name'=>'Kapasia'],
            ['district_id'=>'41', 'bn_name'=>'গাজীপুর সদর', 'name'=>'Gazipur Sadar'],
            ['district_id'=>'41', 'bn_name'=>'শ্রীপুর', 'name'=>'Sreepur'],
            ['district_id'=>'42', 'bn_name'=>'শরিয়তপুর সদর', 'name'=>'Shariatpur Sadar'],
            ['district_id'=>'42', 'bn_name'=>'নড়িয়া', 'name'=>'Naria'],
            ['district_id'=>'42', 'bn_name'=>'জাজিরা', 'name'=>'Zajira'],
            ['district_id'=>'42', 'bn_name'=>'গোসাইরহাট', 'name'=>'Gosairhat'],
            ['district_id'=>'42', 'bn_name'=>'ভেদরগঞ্জ', 'name'=>'Bhedarganj'],
            ['district_id'=>'42', 'bn_name'=>'ডামুড্যা', 'name'=>'Damudya'],
            ['district_id'=>'43', 'bn_name'=>'আড়াইহাজার', 'name'=>'Araihazar'],
            ['district_id'=>'43', 'bn_name'=>'বন্দর', 'name'=>'Bandar'],
            ['district_id'=>'43', 'bn_name'=>'নারায়নগঞ্জ সদর', 'name'=>'Narayanganj Sadar'],
            ['district_id'=>'43', 'bn_name'=>'রূপগঞ্জ', 'name'=>'Rupganj'],
            ['district_id'=>'43', 'bn_name'=>'সোনারগাঁ', 'name'=>'Sonargaon'],
            ['district_id'=>'44', 'bn_name'=>'বাসাইল', 'name'=>'Basail'],
            ['district_id'=>'44', 'bn_name'=>'ভুয়াপুর', 'name'=>'Bhuapur'],
            ['district_id'=>'44', 'bn_name'=>'দেলদুয়ার', 'name'=>'Delduar'],
            ['district_id'=>'44', 'bn_name'=>'ঘাটাইল', 'name'=>'Ghatail'],
            ['district_id'=>'44', 'bn_name'=>'গোপালপুর', 'name'=>'Gopalpur'],
            ['district_id'=>'44', 'bn_name'=>'মধুপুর', 'name'=>'Madhupur'],
            ['district_id'=>'44', 'bn_name'=>'মির্জাপুর', 'name'=>'Mirzapur'],
            ['district_id'=>'44', 'bn_name'=>'নাগরপুর', 'name'=>'Nagarpur'],
            ['district_id'=>'44', 'bn_name'=>'সখিপুর', 'name'=>'Sakhipur'],
            ['district_id'=>'44', 'bn_name'=>'টাঙ্গাইল সদর', 'name'=>'Tangail Sadar'],
            ['district_id'=>'44', 'bn_name'=>'কালিহাতী', 'name'=>'Kalihati'],
            ['district_id'=>'44', 'bn_name'=>'ধনবাড়ী', 'name'=>'Dhanbari'],
            ['district_id'=>'45', 'bn_name'=>'ইটনা', 'name'=>'Itna'],
            ['district_id'=>'45', 'bn_name'=>'কটিয়াদী', 'name'=>'Katiadi'],
            ['district_id'=>'45', 'bn_name'=>'ভৈরব', 'name'=>'Bhairab'],
            ['district_id'=>'45', 'bn_name'=>'তাড়াইল', 'name'=>'Tarail'],
            ['district_id'=>'45', 'bn_name'=>'হোসেনপুর', 'name'=>'Hossainpur'],
            ['district_id'=>'45', 'bn_name'=>'পাকুন্দিয়া', 'name'=>'Pakundia'],
            ['district_id'=>'45', 'bn_name'=>'কুলিয়ারচর', 'name'=>'Kuliarchar'],
            ['district_id'=>'45', 'bn_name'=>'কিশোরগঞ্জ সদর', 'name'=>'Kishoreganj Sadar'],
            ['district_id'=>'45', 'bn_name'=>'করিমগঞ্জ', 'name'=>'Karimgonj'],
            ['district_id'=>'45', 'bn_name'=>'বাজিতপুর', 'name'=>'Bajitpur'],
            ['district_id'=>'45', 'bn_name'=>'অষ্টগ্রাম', 'name'=>'Austagram'],
            ['district_id'=>'45', 'bn_name'=>'মিঠামইন', 'name'=>'Mithamoin'],
            ['district_id'=>'45', 'bn_name'=>'নিকলী', 'name'=>'Nikli'],
            ['district_id'=>'46', 'bn_name'=>'হরিরামপুর', 'name'=>'Harirampur'],
            ['district_id'=>'46', 'bn_name'=>'সাটুরিয়া', 'name'=>'Saturia'],
            ['district_id'=>'46', 'bn_name'=>'মানিকগঞ্জ সদর', 'name'=>'Manikganj Sadar'],
            ['district_id'=>'46', 'bn_name'=>'ঘিওর', 'name'=>'Gior'],
            ['district_id'=>'46', 'bn_name'=>'শিবালয়', 'name'=>'Shibaloy'],
            ['district_id'=>'46', 'bn_name'=>'দৌলতপুর', 'name'=>'Doulatpur'],
            ['district_id'=>'46', 'bn_name'=>'সিংগাইর', 'name'=>'Singiar'],
            ['district_id'=>'47', 'bn_name'=>'সাভার', 'name'=>'Savar'],
            ['district_id'=>'47', 'bn_name'=>'ধামরাই', 'name'=>'Dhamrai'],
            ['district_id'=>'47', 'bn_name'=>'কেরাণীগঞ্জ', 'name'=>'Keraniganj'],
            ['district_id'=>'47', 'bn_name'=>'নবাবগঞ্জ', 'name'=>'Nawabganj'],
            ['district_id'=>'47', 'bn_name'=>'দোহার', 'name'=>'Dohar'],
            ['district_id'=>'48', 'bn_name'=>'মুন্সিগঞ্জ সদর', 'name'=>'Munshiganj Sadar'],
            ['district_id'=>'48', 'bn_name'=>'শ্রীনগর', 'name'=>'Sreenagar'],
            ['district_id'=>'48', 'bn_name'=>'সিরাজদিখান', 'name'=>'Sirajdikhan'],
            ['district_id'=>'48', 'bn_name'=>'লৌহজং', 'name'=>'Louhajanj'],
            ['district_id'=>'48', 'bn_name'=>'গজারিয়া', 'name'=>'Gajaria'],
            ['district_id'=>'48', 'bn_name'=>'টংগীবাড়ি', 'name'=>'Tongibari'],
            ['district_id'=>'49', 'bn_name'=>'রাজবাড়ী সদর', 'name'=>'Rajbari Sadar'],
            ['district_id'=>'49', 'bn_name'=>'গোয়ালন্দ', 'name'=>'Goalanda'],
            ['district_id'=>'49', 'bn_name'=>'পাংশা', 'name'=>'Pangsa'],
            ['district_id'=>'49', 'bn_name'=>'বালিয়াকান্দি', 'name'=>'Baliakandi'],
            ['district_id'=>'49', 'bn_name'=>'কালুখালী', 'name'=>'Kalukhali'],
            ['district_id'=>'50', 'bn_name'=>'মাদারীপুর সদর', 'name'=>'Madaripur Sadar'],
            ['district_id'=>'50', 'bn_name'=>'শিবচর', 'name'=>'Shibchar'],
            ['district_id'=>'50', 'bn_name'=>'কালকিনি', 'name'=>'Kalkini'],
            ['district_id'=>'50', 'bn_name'=>'রাজৈর', 'name'=>'Rajoir'],
            ['district_id'=>'51', 'bn_name'=>'গোপালগঞ্জ সদর', 'name'=>'Gopalganj Sadar'],
            ['district_id'=>'51', 'bn_name'=>'কাশিয়ানী', 'name'=>'Kashiani'],
            ['district_id'=>'51', 'bn_name'=>'টুংগীপাড়া', 'name'=>'Tungipara'],
            ['district_id'=>'51', 'bn_name'=>'কোটালীপাড়া', 'name'=>'Kotalipara'],
            ['district_id'=>'51', 'bn_name'=>'মুকসুদপুর', 'name'=>'Muksudpur'],
            ['district_id'=>'52', 'bn_name'=>'ফরিদপুর সদর', 'name'=>'Faridpur Sadar'],
            ['district_id'=>'52', 'bn_name'=>'আলফাডাঙ্গা', 'name'=>'Alfadanga'],
            ['district_id'=>'52', 'bn_name'=>'বোয়ালমারী', 'name'=>'Boalmari'],
            ['district_id'=>'52', 'bn_name'=>'সদরপুর', 'name'=>'Sadarpur'],
            ['district_id'=>'52', 'bn_name'=>'নগরকান্দা', 'name'=>'Nagarkanda'],
            ['district_id'=>'52', 'bn_name'=>'ভাঙ্গা', 'name'=>'Bhanga'],
            ['district_id'=>'52', 'bn_name'=>'চরভদ্রাসন', 'name'=>'Charbhadrasan'],
            ['district_id'=>'52', 'bn_name'=>'মধুখালী', 'name'=>'Madhukhali'],
            ['district_id'=>'52', 'bn_name'=>'সালথা', 'name'=>'Saltha'],
            ['district_id'=>'53', 'bn_name'=>'পঞ্চগড় সদর', 'name'=>'Panchagarh Sadar'],
            ['district_id'=>'53', 'bn_name'=>'দেবীগঞ্জ', 'name'=>'Debiganj'],
            ['district_id'=>'53', 'bn_name'=>'বোদা', 'name'=>'Boda'],
            ['district_id'=>'53', 'bn_name'=>'আটোয়ারী', 'name'=>'Atwari'],
            ['district_id'=>'53', 'bn_name'=>'তেতুলিয়া', 'name'=>'Tetulia'],
            ['district_id'=>'54', 'bn_name'=>'নবাবগঞ্জ', 'name'=>'Nawabganj'],
            ['district_id'=>'54', 'bn_name'=>'বীরগঞ্জ', 'name'=>'Birganj'],
            ['district_id'=>'54', 'bn_name'=>'ঘোড়াঘাট', 'name'=>'Ghoraghat'],
            ['district_id'=>'54', 'bn_name'=>'বিরামপুর', 'name'=>'Birampur'],
            ['district_id'=>'54', 'bn_name'=>'পার্বতীপুর', 'name'=>'Parbatipur'],
            ['district_id'=>'54', 'bn_name'=>'বোচাগঞ্জ', 'name'=>'Bochaganj'],
            ['district_id'=>'54', 'bn_name'=>'কাহারোল', 'name'=>'Kaharol'],
            ['district_id'=>'54', 'bn_name'=>'ফুলবাড়ী', 'name'=>'Fulbari'],
            ['district_id'=>'54', 'bn_name'=>'দিনাজপুর সদর', 'name'=>'Dinajpur Sadar'],
            ['district_id'=>'54', 'bn_name'=>'হাকিমপুর', 'name'=>'Hakimpur'],
            ['district_id'=>'54', 'bn_name'=>'খানসামা', 'name'=>'Khansama'],
            ['district_id'=>'54', 'bn_name'=>'বিরল', 'name'=>'Birol'],
            ['district_id'=>'54', 'bn_name'=>'চিরিরবন্দর', 'name'=>'Chirirbandar'],
            ['district_id'=>'55', 'bn_name'=>'লালমনিরহাট সদর', 'name'=>'Lalmonirhat Sadar'],
            ['district_id'=>'55', 'bn_name'=>'কালীগঞ্জ', 'name'=>'Kaliganj'],
            ['district_id'=>'55', 'bn_name'=>'হাতীবান্ধা', 'name'=>'Hatibandha'],
            ['district_id'=>'55', 'bn_name'=>'পাটগ্রাম', 'name'=>'Patgram'],
            ['district_id'=>'55', 'bn_name'=>'আদিতমারী', 'name'=>'Aditmari'],
            ['district_id'=>'56', 'bn_name'=>'সৈয়দপুর', 'name'=>'Syedpur'],
            ['district_id'=>'56', 'bn_name'=>'ডোমার', 'name'=>'Domar'],
            ['district_id'=>'56', 'bn_name'=>'ডিমলা', 'name'=>'Dimla'],
            ['district_id'=>'56', 'bn_name'=>'জলঢাকা', 'name'=>'Jaldhaka'],
            ['district_id'=>'56', 'bn_name'=>'কিশোরগঞ্জ', 'name'=>'Kishorganj'],
            ['district_id'=>'56', 'bn_name'=>'নীলফামারী সদর', 'name'=>'Nilphamari Sadar'],
            ['district_id'=>'57', 'bn_name'=>'সাদুল্লাপুর', 'name'=>'Sadullapur'],
            ['district_id'=>'57', 'bn_name'=>'গাইবান্ধা সদর', 'name'=>'Gaibandha Sadar'],
            ['district_id'=>'57', 'bn_name'=>'পলাশবাড়ী', 'name'=>'Palashbari'],
            ['district_id'=>'57', 'bn_name'=>'সাঘাটা', 'name'=>'Saghata'],
            ['district_id'=>'57', 'bn_name'=>'গোবিন্দগঞ্জ', 'name'=>'Gobindaganj'],
            ['district_id'=>'57', 'bn_name'=>'সুন্দরগঞ্জ', 'name'=>'Sundarganj'],
            ['district_id'=>'57', 'bn_name'=>'ফুলছড়ি', 'name'=>'Phulchari'],
            ['district_id'=>'58', 'bn_name'=>'ঠাকুরগাঁও সদর', 'name'=>'Thakurgaon Sadar'],
            ['district_id'=>'58', 'bn_name'=>'পীরগঞ্জ', 'name'=>'Pirganj'],
            ['district_id'=>'58', 'bn_name'=>'রাণীশংকৈল', 'name'=>'Ranisankail'],
            ['district_id'=>'58', 'bn_name'=>'হরিপুর', 'name'=>'Haripur'],
            ['district_id'=>'58', 'bn_name'=>'বালিয়াডাঙ্গী', 'name'=>'Baliadangi'],
            ['district_id'=>'59', 'bn_name'=>'রংপুর সদর', 'name'=>'Rangpur Sadar'],
            ['district_id'=>'59', 'bn_name'=>'গংগাচড়া', 'name'=>'Gangachara'],
            ['district_id'=>'59', 'bn_name'=>'তারাগঞ্জ', 'name'=>'Taragonj'],
            ['district_id'=>'59', 'bn_name'=>'বদরগঞ্জ', 'name'=>'Badargonj'],
            ['district_id'=>'59', 'bn_name'=>'মিঠাপুকুর', 'name'=>'Mithapukur'],
            ['district_id'=>'59', 'bn_name'=>'পীরগঞ্জ', 'name'=>'Pirgonj'],
            ['district_id'=>'59', 'bn_name'=>'কাউনিয়া', 'name'=>'Kaunia'],
            ['district_id'=>'59', 'bn_name'=>'পীরগাছা', 'name'=>'Pirgacha'],
            ['district_id'=>'60', 'bn_name'=>'কুড়িগ্রাম সদর', 'name'=>'Kurigram Sadar'],
            ['district_id'=>'60', 'bn_name'=>'নাগেশ্বরী', 'name'=>'Nageshwari'],
            ['district_id'=>'60', 'bn_name'=>'ভুরুঙ্গামারী', 'name'=>'Bhurungamari'],
            ['district_id'=>'60', 'bn_name'=>'ফুলবাড়ী', 'name'=>'Phulbari'],
            ['district_id'=>'60', 'bn_name'=>'রাজারহাট', 'name'=>'Rajarhat'],
            ['district_id'=>'60', 'bn_name'=>'উলিপুর', 'name'=>'Ulipur'],
            ['district_id'=>'60', 'bn_name'=>'চিলমারী', 'name'=>'Chilmari'],
            ['district_id'=>'60', 'bn_name'=>'রৌমারী', 'name'=>'Rowmari'],
            ['district_id'=>'60', 'bn_name'=>'চর রাজিবপুর', 'name'=>'Charrajibpur'],
            ['district_id'=>'61', 'bn_name'=>'শেরপুর সদর', 'name'=>'Sherpur Sadar'],
            ['district_id'=>'61', 'bn_name'=>'নালিতাবাড়ী', 'name'=>'Nalitabari'],
            ['district_id'=>'61', 'bn_name'=>'শ্রীবরদী', 'name'=>'Sreebordi'],
            ['district_id'=>'61', 'bn_name'=>'নকলা', 'name'=>'Nokla'],
            ['district_id'=>'61', 'bn_name'=>'ঝিনাইগাতী', 'name'=>'Jhenaigati'],
            ['district_id'=>'62', 'bn_name'=>'ফুলবাড়ীয়া', 'name'=>'Fulbaria'],
            ['district_id'=>'62', 'bn_name'=>'ত্রিশাল', 'name'=>'Trishal'],
            ['district_id'=>'62', 'bn_name'=>'ভালুকা', 'name'=>'Bhaluka'],
            ['district_id'=>'62', 'bn_name'=>'মুক্তাগাছা', 'name'=>'Muktagacha'],
            ['district_id'=>'62', 'bn_name'=>'ময়মনসিংহ সদর', 'name'=>'Mymensingh Sadar'],
            ['district_id'=>'62', 'bn_name'=>'ধোবাউড়া', 'name'=>'Dhobaura'],
            ['district_id'=>'62', 'bn_name'=>'ফুলপুর', 'name'=>'Phulpur'],
            ['district_id'=>'62', 'bn_name'=>'হালুয়াঘাট', 'name'=>'Haluaghat'],
            ['district_id'=>'62', 'bn_name'=>'গৌরীপুর', 'name'=>'Gouripur'],
            ['district_id'=>'62', 'bn_name'=>'গফরগাঁও', 'name'=>'Gafargaon'],
            ['district_id'=>'62', 'bn_name'=>'ঈশ্বরগঞ্জ', 'name'=>'Iswarganj'],
            ['district_id'=>'62', 'bn_name'=>'নান্দাইল', 'name'=>'Nandail'],
            ['district_id'=>'62', 'bn_name'=>'তারাকান্দা', 'name'=>'Tarakanda'],
            ['district_id'=>'63', 'bn_name'=>'জামালপুর সদর', 'name'=>'Jamalpur Sadar'],
            ['district_id'=>'63', 'bn_name'=>'মেলান্দহ', 'name'=>'Melandah'],
            ['district_id'=>'63', 'bn_name'=>'ইসলামপুর', 'name'=>'Islampur'],
            ['district_id'=>'63', 'bn_name'=>'দেওয়ানগঞ্জ', 'name'=>'Dewangonj'],
            ['district_id'=>'63', 'bn_name'=>'সরিষাবাড়ী', 'name'=>'Sarishabari'],
            ['district_id'=>'63', 'bn_name'=>'মাদারগঞ্জ', 'name'=>'Madarganj'],
            ['district_id'=>'63', 'bn_name'=>'বকশীগঞ্জ', 'name'=>'Bokshiganj'],
            ['district_id'=>'64', 'bn_name'=>'বারহাট্টা', 'name'=>'Barhatta'],
            ['district_id'=>'64', 'bn_name'=>'দুর্গাপুর', 'name'=>'Durgapur'],
            ['district_id'=>'64', 'bn_name'=>'কেন্দুয়া', 'name'=>'Kendua'],
            ['district_id'=>'64', 'bn_name'=>'আটপাড়া', 'name'=>'Atpara'],
            ['district_id'=>'64', 'bn_name'=>'মদন', 'name'=>'Madan'],
            ['district_id'=>'64', 'bn_name'=>'খালিয়াজুরী', 'name'=>'Khaliajuri'],
            ['district_id'=>'64', 'bn_name'=>'কলমাকান্দা', 'name'=>'Kalmakanda'],
            ['district_id'=>'64', 'bn_name'=>'মোহনগঞ্জ', 'name'=>'Mohongonj'],
            ['district_id'=>'64', 'bn_name'=>'পূর্বধলা', 'name'=>'Purbadhala'],
            ['district_id'=>'64', 'bn_name'=>'নেত্রকোণা সদর', 'name'=>'Netrokona Sadar'],

        ];
        DB::table('upazilas')->insert($upazila);
    }
}
